db_hosts:
 hosts:
    ansible:
        ansible_host: ansible-foal.gpx.cz
        pg_instances:
        - name: 12-main
          databases:
          - first
          - second
          port: 5430
        - databases:
          - another
          - other
          name: 12-devel
          port: 5433
        - databases:
          - magic
          name: 11-devel
          port: 5434

    worker:
        ansible_host: worker-foal.gpx.cz
        pg_instances:
        - name: 12-main
          databases:
          - first
          - second
          port: 5430

